### ISSUE TITLE
Is this repo outdated?

### ISSUE THREAD

**Issue by wuori** [Runara/test#1]
I really apologize for nagging you and interrupting your evening, and if I don't hear anything from you, you won't be bothered again.

I'd really like to use the name "Runara" for my github account. Github's TOS prevent me from trying to buy it from you, but if you're not planning on using it anymore I'd love to take it off your hands. 

If you're still using this or plan to (or just don't care either way), then no worries! Happy coding!

Again, sorry for the intrusion! I just couldn't find any other way to contact you.

**Comment by TajkaM** [comment]
Hi. This account was created for testing. If you need I can delete my account and
you can creat it with this name. If you are still interested email me.

. 

  25.01.2017, 3:14:29 пользователь Michael Wuori (notifications@github.com)
  написал:


  I really apologize for nagging you and interrupting your evening, and if I
  don't hear anything from you, you won't be bothered again.

  I'd really like to use the name "Runara" for my github account. Github's TOS
  prevent me from trying to buy it from you, but if you're not planning on
  using it anymore I'd love to take it off your hands.

  If you're still using this or plan to (or just don't care either way), then
  no worries! Happy coding!

  Again, sorry for the intrusion! I just couldn't find any other way to contact
  you.

**Comment by wuori** [comment]
@Runara Yes, I'm still interested, thank you so much for getting back to me! I don't have your email address, but you can reach me at michael.wuori@gmail.com or comment with yours and I'll message you. Thanks again!

**Comment by TajkaM** [comment]
Hi. I changed my name, "Runara" must be free. Try to use it. :))

. 

  07.02.2017, 17:02:51 пользователь Michael Wuori (notifications@github.com)
  написал:


  @Runara Yes, I'm still interested, thank you so much for getting back to me!
  I don't have your email address, but you can reach me at
  michael.wuori@gmail.com or comment with yours and I'll message you. Thanks
  again!
